
[Spawning]
	#You can boost the frequency of the obsessed stalking its targets by increasing this number (4,000 default), or decrease it by lowering it (minimum=0, maximum effect=6000)
	"Stalk Frequency" = 4000.0
	#You can boost the frequency of the original targeting version of the obsessed by increasing this number (2400 default), or decrease it by lowering it (minimum=0, maximum effect=4600)
	"Natural Targeter Spawnrate" = 2400.0

[Difficulty]
	#Minimum 1.0, default 5.0. Controls how many obsessed spawns occur before each time its mood decreases automatically. E.g. with default value of 10.0, every eight times it spawns, it will decrease its mood by 1 point (mood range is -5 to 5).
	"Obsessed Patience" = 8.0

[Other]
	#Set to false to disable the initial welcome text shown to players on first world load
	"Splash Text" = true
	#Allow multiple players to be targeted, or only one per world? Set to true if you would like to allow multiple obsessions at a time.
	"Allow Multiple Targets" = false
	#Set to false to disable hallucination entities. This includes the bed version, block breaking version, targeter popup, and lightning strike spider version
	"Enable Hallucination Entities" = true
	#FALSE by default. If you set this to true, it is recommended to also set Allow Multiple Targets to true. Enables creative/spectator mode players to retain obsessed targeting.
	"Allow Targeting Creative/Spectator Players" = false
	#Enabled by default. The Obsessed can open wooden doors, replace regular torches with redstone equivalents, and plant wither roses in intruder mode, and break leaves, non-stained glass, and doors when abducting. Plus it places blocks sometimes in the mimicking mode. Set to false to prevent these
	"Allow Obsessed Griefing" = true
	#If you do not have the above 'allow multiple targets' mode enabled, the obsessed will lose interest after X amount of seconds of its target player not being on the server, or being in a non-overworld dimension continuously. 1200 seconds by default (20 minutes).
	"Seconds before losing interest in single target mode" = 1200.0

